---
title: "Práctico 3. Modelos Lineales Múltiples I"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Caso 1

Se estudió el efecto del número de parejas sexuales sobre la longevidad de moscas de la fruta macho. Los tratamientos fueron: A = control (sin hembras), B = control (una hembra no receptiva al día), C = control (8 hembras no receptivas al día), D = una hembra virgen al día, E = 8 hembras vírgenes al día. Ya que la longevidad puede estar relacionada con el tamaño del insecto se tomó el diámetro del tórax como covariable. Los datos se encuentran en el archivo moscas.txt.  

```R
## Caso 1. 
library(car)  
library(performance)

dat <- read.table("moscas.txt", header = TRUE, stringsAsFactors = TRUE)

plot(dat$torax)
plot(dat$vida)
plot(dat$trat,dat$vida)
plot(dat$torax,dat$vida)

#diferentes sumas de cuadrados (ejemplo didáctico)
# BAJO NINGUNA CIRCUSNTANCIA DEBEN PROBARSE DIFERENTES SUMAS DE CUADRADOS
# NO SON HERRAMIENTAS EXPLORATORIAS, SINO QUE SE ESTABLECEN EN EL DISEÑO
fit1.a <- lm(vida ~ trat*torax, data = dat)
fit1.b <- lm(vida ~ torax*trat, data = dat)

# Tipo 1
anova(fit1.a) 
anova(fit1.b)

# Tipo 2
Anova(fit1.a, type = "II")
Anova(fit1.b, type = "II")

# Tipo 3
Anova(fit1.a, type = "III")
Anova(fit1.b, type = "III")

# revisando el resultado 
summary(fit1.a)
layout(matrix(1:4, 2, 2))
plot(fit1.a)
layout(1)


# selección del modelo basado en significancia
fit1 <- lm(vida ~ trat * torax, data = dat)
fit2 <- lm(vida ~ trat + torax, data = dat)
fit3 <- lm(vida ~ trat, data =dat)
fit4 <- lm(vida ~ torax, data =dat)
fit5 <- lm(vida ~ 1, data =dat)

anova(fit1, fit2, fit3, fit4, fit5) #comparación secuencial
compare_performance(fit1, fit2, fit3, fit4, fit5) # criterios

# revisando el modelo final
layout(matrix(1:4, 2, 2))
plot(fit3)
layout(1)

```

## Ejercicios

1. Se busca un modelo que prediga la biomasa (peso.seco) de las almejas en función de su largo máximo (largo). Debido al ciclo de vida de las almejas, la relación biomasa-largo puede variar a lo largo del año, por lo que se ha tomado el mes de colecta (mes) como covariable. Los datos para el ejercicio se encuentran en el archivo almejas.txt.   

2. Se intenta determinar el efecto de la estación (IP= invierno/primavera vs. VO= verano/otoño) y la densidad de adultos (A=8, B=15, C=30, D=45 en 225 cm2) sobre la producción de huevos de bivalvos. Los datos para el ejercicio se encuentran en el archivo bivalvos.txt.  

3. Los datos del archivo fumadores.txt corresponden a un estudio donde se intenta explicar la capacidad pulmonar en función de dos variables continuas (edad y altura) y dos variables discretas (fumar = si/no; sexo = m/f). ¿No le parece un poco raro el resultado?